# Generated by Django 2.1.4 on 2019-01-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=5)),
                ('consumption', models.CharField(max_length=10)),
                ('length', models.CharField(max_length=10)),
                ('recommended_speed', models.CharField(max_length=10)),
                ('coeff_roughness', models.CharField(max_length=10)),
            ],
        ),
    ]
